"""Generate budget documentation and evaluation metadata from review_config.py."""
import argparse
import json
from pathlib import Path

from review_config import TIER_REQUIREMENTS, WORD_BUDGETS, SEARCH_REQUIREMENTS, CLAIM_RANGES, DECK_BUDGETS
from artifact_io import atomic_write_json, atomic_write_text


def profile(size):
    return {"tier": TIER_REQUIREMENTS[size], "words": {s: v[size] for s, v in WORD_BUDGETS.items()},
            "search": SEARCH_REQUIREMENTS[size], "claims": CLAIM_RANGES[size], "slides": DECK_BUDGETS[size]}


def documentation():
    def bounds(value):
        return f"{value[0]}+" if value[1] is None else f"{value[0]}–{value[1]}"
    rows = ["# Review budgets", "", "Generated by `scripts/sync_review_budgets.py`; edit `scripts/review_config.py`.",
            "Source ranges are planning guidance, never inclusion quotas. Search saturation and relevance take precedence.",
            "", "| Budget | Small | Medium | Large |", "|---|---|---|---|"]
    for label, values in (
        ("Scientific/popsci words", WORD_BUDGETS["scientific"]),
        ("Bullets/ELI5 words", WORD_BUDGETS["bullets"]),
        *((name, {s: v[name] for s, v in TIER_REQUIREMENTS.items()})
          for name in ("sections", "sources", "tables", "fulltexts")),
        ("Synthesis claims", CLAIM_RANGES),
        *((name, {s: v[name] for s, v in SEARCH_REQUIREMENTS.items()})
          for name in ("angles", "queries")),
    ):
        rows.append("| " + label + " | " + " | ".join(bounds(values[s]) for s in TIER_REQUIREMENTS) + " |")
    rows.append("| PDF figures | " + " | ".join(f"target {v['figure_target']}, cap {v['figure_cap']}" for v in TIER_REQUIREMENTS.values()) + " |")
    for key in ("content", "total"):
        rows.append("| Slides " + key + " | " + " | ".join(bounds(DECK_BUDGETS[s][key]) for s in TIER_REQUIREMENTS) + " |")
    return "\n".join(rows) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--evals", type=Path)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    doc = root / "references" / "budgets.md"
    expected = documentation()
    stale = []
    if args.check:
        if not doc.is_file() or doc.read_text() != expected:
            stale.append(str(doc))
    else:
        atomic_write_text(doc, expected)
    if args.evals:
        data = json.loads(args.evals.read_text())
        generated = {size: profile(size) for size in TIER_REQUIREMENTS}
        generated = json.loads(json.dumps(generated))
        if args.check:
            if data.get("budget_profiles") != generated:
                stale.append(str(args.evals))
        else:
            data["budget_profiles"] = generated
            atomic_write_json(args.evals, data)
    if stale:
        raise SystemExit("stale generated budgets: " + ", ".join(stale))


if __name__ == "__main__":
    main()
